### PR TITLE
feature: algolia search

### LINKED ISSUE #141: Search functionality for dataguide
As per discussion here: https://prisma-company.slack.com/archives/CJ5U1BS2X/p1618386028009300

Basically just porting the search functionality from the docs to the data guide.

### PR DESCRIPTION
**Pull request by carlagn**
Fixes #141

### CODE REVIEW

**Comment by nilubava** [comment]
@carlagn This PR has only the UI part of the search functionality. We need to implement the algolia plugin too - Refer `docs/plugins/gatsby-algolia-indexer`

**Comment by meletj** [comment]
Justin's feedback: 
Looks pretty good so far. I like the placement of the search bar on the main index page.  I think one thing functionally that was a bit confusing is that the modal blocks the view of the search box.  For example, if you type the first one or two characters, the modal will pop up and cover the input field. You can tell where you are in your typing from context based on the highlighted portion of the results, but it’s not too obvious and it makes editing more difficult.
nother thing I noticed is that if you hit ESC to exit out of the modal, it dismisses after a moment.  However, the typed entry in the search box isn’t cleared, so when you click the search box again, it brings the modal right back up.  It might make sense to clear the entered text if you’ve dismissed the modal.  This probably matters much less though if the input field was still visible when the modal pops up.

**Review by meletj — CHANGES_REQUESTED** [review]
**Design**: 
- [x] on Data Guide homepage, the 'Share on twitter' should be removed (covered by new search box)

**Functionality - from homepage**
- Is this expected behavior that the search box opens at top of the hero on the homepage? Could we do it the same way as on the individual pages? 
- the Search itself returns results but when I click on one it doesn't take me to that page/section. Sort of goes there for 1 sec then returns to homepage

Functionality - from individual pages
- same issue with search function; it quickly goes to the page/section but then returns to whatever page I was originally on

**Comment by carlagn** [comment]
> **Design**:
> 
> * [ ]  on Data Guide homepage, the 'Share on twitter' should be removed (covered by new search box)
> 
> **Functionality - from homepage**
> 
> * Is this expected behavior that the search box opens at top of the hero on the homepage? Could we do it the same way as on the individual pages?
> * the Search itself returns results but when I click on one it doesn't take me to that page/section. Sort of goes there for 1 sec then returns to homepage
> 
> Functionality - from individual pages
> 
> * same issue with search function; it quickly goes to the page/section but then returns to whatever page I was originally on

1. Design has been updated.
2. The search box opens at the top so the input is visible and editable to the user. I didn't put the same behaviour on the header search bar since it's already at the top but I can update to have the same behavior. 
3. Functionality has been fixed! I've re-checked with the preview and it seems to be working as expected. If you could take 5min to double check as well I'd appreciate it!

**Comment by meletj** [comment]
Not sure if can adjust this but the search seems to always show the conclusion/faq/end of an article as the results. It's bit odd. Do you see what I mean? 
Screenshot 2022-10-25 at 09 17 23

**Comment by meletj** [comment]
> The search box opens at the top so the input is visible and editable to the user. I didn't put the same behaviour on the header search bar since it's already at the top but I can update to have the same behavior.
I was thinking we could do the same behaviour as on individual pages ie the overlay just goes on top of the actual search box rather than moving up at the top.

**Review by nilubava — APPROVED** [review]

**Review by meletj — APPROVED** [review]

**Review by nilubava — APPROVED** [review]

**Pull request merged**
