### PR TITLE
Add connection pooling article

### PR DESCRIPTION
**Pull request by imchairmanm**

### CODE REVIEW

**Review by alex-emerich — APPROVED** [review]
Really well done. Enjoyed reading this article a lot 👍

**Comment by janpio** [comment]
The one thing related to this, I would love to have a linkable resource for the difference between the two different kinds of conneciton pooling: Application level (like in Prisma Client, where you have a pool in the Engine that opens x connections so x requests can be done in parallel) and server level (like with PgBouncer, where you have a "proxy" in front of your database that pools connections and brokers the incoming SQL queries between them). Right now people do not understand the difference, which makes conversation around this topic harder.

**Comment by imchairmanm** [comment]
> The one thing related to this, I would love to have a linkable resource for the difference between the two different kinds of conneciton pooling: Application level (like in Prisma Client, where you have a pool in the Engine that opens x connections so x requests can be done in parallel) and server level (like with PgBouncer, where you have a "proxy" in front of your database that pools connections and brokers the incoming SQL queries between them). Right now people do not understand the difference, which makes conversation around this topic harder.

Thanks for the feedback Jan. I added a section that I hope addresses that concern, but referred to it as internal vs external pooling.

**Comment by janpio** [comment]
Are those standing, known terms or something you came up with to give it a name?

I like the explanation very much. Would be interested in reading other discussions of this though as well.

**Comment by imchairmanm** [comment]
I'm not sure if there are any standard terms for the difference you're describing, so I think those are probably just terms I came up with.  I was hesitant to use "application level" vs "server level" because implementations like `pgbouncer` can be deployed (depending on what you're trying to achieve) on the database server, on the application server, or anywhere in between the two, which I assume muddles the distinction you're trying to make.

A lot of the information I found about built-in pooling functionality were coming from the Java ecosystem (discussing JDBC's implementation, some pages on Hibernate, etc.).  I had a harder time finding more general resources about that functionality within DB clients or drivers.

**Pull request merged**
